"""feat: add user_id

Revision ID: a2e0c001ea4d
Revises: 526198c2ee75
Create Date: 2025-12-07 17:48:52.790868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2e0c001ea4d'
down_revision: Union[str, Sequence[str], None] = '526198c2ee75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_material_user_id'), 'material', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_user_id'), table_name='material')
    op.drop_column('material', 'user_id')
    # ### end Alembic commands ###
